import {
  type BorrowerInput,
  type EngineResult,
  inr,
  productLabel,
} from '../engine/rules';

/**
 * Negotiation Card — designed to be printed and brought to the bank branch.
 *
 * Layout (per assignment):
 *   - Recommended borrowing + lender sanction + safe EMI
 *   - Fair rate range + processing fee + estimated APR
 *   - Recommended tenure
 *   - "What to ask the lender" — 6 specific counter-prompts
 *   - "Why this range" — 3–5 persona-specific reasons
 *   - Stress check — one short scenario
 */
export default function NegotiationCard({
  input,
  result,
}: {
  input: BorrowerInput;
  result: EngineResult;
}) {
  const { verdict, capacity, rate, stress } = result;
  const recommended = capacity.recommendedCapacity;
  const tenure = result.recommendedTenureMonths;

  return (
    <article className="print-card rounded-lg border border-slate-300 bg-white p-6 sm:p-8 shadow-sm">
      <header className="flex items-baseline justify-between border-b border-slate-200 pb-3 mb-4">
        <div>
          <div className="text-xs uppercase tracking-wider text-slate-500">Negotiation Card</div>
          <h2 className="text-lg font-semibold text-slate-900">Take this to the bank branch</h2>
        </div>
        <div className="text-right">
          <div className="text-xs text-slate-500">Verdict</div>
          <div className="text-base font-semibold text-slate-900">{verdict.verdict}</div>
        </div>
      </header>

      {/* The numbers */}
      <div className="grid sm:grid-cols-2 gap-4 mb-5">
        <Row label="Recommended borrowing" value={inr(recommended)} highlight />
        <Row label="Likely lender sanction" value={inr(capacity.lenderSanctionMax)} />
        <Row label="Maximum safe EMI" value={inr(stress.safeEmi)} />
        <Row label="Recommended tenure" value={`${tenure} months`} />
        <Row label="Fair interest rate" value={`${rate.rateMin}% – ${rate.rateMax}% p.a.`} />
        <Row label="Processing fee" value={`${(rate.processingFeePct * 100).toFixed(2)}% of principal (upfront)`} />
        <Row label="Estimated all-in APR" value={`${rate.aprMin}% – ${rate.aprMax}%`} />
        <Row label="Recommended product" value={productLabel(rate.recommendedProduct)} />
      </div>

      {/* What to ask */}
      <section className="mb-5">
        <h3 className="text-sm font-semibold text-slate-900 mb-2">What to ask the lender</h3>
        <ul className="list-disc pl-5 space-y-1 text-sm text-slate-700">
          <li>Rate at or below the fair range above.</li>
          <li>Processing fee in writing — no hidden line items.</li>
          <li>Final APR / all-in cost — make them quote it, not just the headline rate.</li>
          <li>EMI for my recommended tenure and amount.</li>
          <li>Mandatory insurance or add-on charges, if any.</li>
          <li>Foreclosure / prepayment penalty terms.</li>
        </ul>
      </section>

      {/* Why this range */}
      <section className="mb-5">
        <h3 className="text-sm font-semibold text-slate-900 mb-2">Why this range</h3>
        <ul className="list-disc pl-5 space-y-1 text-sm text-slate-700">
          {buildReasons(input, result).map((r, i) => (<li key={i}>{r}</li>))}
        </ul>
      </section>

      {/* Stress check */}
      <section className="rounded-md border border-slate-200 bg-slate-50 p-3 mb-4">
        <h3 className="text-sm font-semibold text-slate-900 mb-1">Stress check</h3>
        <p className="text-sm text-slate-700">{stress.scenarios[0].rationale.text}</p>
      </section>

      {/* Methodology note */}
      <details className="text-xs text-slate-600 mb-2">
        <summary className="cursor-pointer">Methodology note — how this was calculated</summary>
        <p className="mt-2 leading-relaxed">
          Estimated APR = nominal rate + (processing fee ÷ tenure in years). This is a simplified
          RBI-style methodology that captures the processing fee but ignores insurance, stamp duty,
          and documentation charges, which can add 0.5–1.5% on retail loans. The result is an
          estimate, not a regulator-grade APR disclosure. FOIR caps are my judgement calibrated to
          common Indian retail practice: 50%/40%/30% lender-side for salaried/self-employed/informal,
          with a 10-percentage-point safer borrower-side cap to leave headroom for income volatility.
        </p>
      </details>

      <footer className="mt-4 pt-3 border-t border-slate-200 text-[10px] text-slate-500">
        Generated by Borrower Copilot · privacy-first, in-browser only · based on rules in RULES.md.
      </footer>
    </article>
  );
}

function Row({ label, value, highlight }: { label: string; value: string; highlight?: boolean }) {
  return (
    <div className={`rounded-md border p-3 ${highlight ? 'border-slate-900 bg-slate-900 text-white' : 'border-slate-200 bg-slate-50'}`}>
      <div className={`text-[10px] uppercase tracking-wide ${highlight ? 'text-slate-300' : 'text-slate-500'}`}>{label}</div>
      <div className={`text-base font-semibold ${highlight ? 'text-white' : 'text-slate-900'}`}>{value}</div>
    </div>
  );
}

function buildReasons(input: BorrowerInput, result: EngineResult): string[] {
  const reasons: string[] = [];

  // Product routing
  if (
    result.rate.recommendedProduct === 'lap' ||
    result.rate.recommendedProduct === 'business_loan'
  ) {
    reasons.push(
      `You own unencumbered collateral — a secured ${productLabel(result.rate.recommendedProduct)} should price roughly half of an unsecured loan.`,
    );
  }

  // Income documentation
  if (input.incomeDocumentation === 'itr') {
    reasons.push('You have filed ITR — lenders will recognise your income at face value.');
  } else if (input.incomeDocumentation === 'bank_statement' || input.incomeDocumentation === 'none') {
    reasons.push(
      `Income is documented as ${input.incomeDocumentation === 'none' ? 'undocumented' : 'bank-statement only'} — expect lenders to apply a documentation surcharge.`,
    );
  }

  // Score
  if (input.cibilScore !== null) {
    reasons.push(`CIBIL ~${input.cibilScore} places you in the ${scoreBand(input.cibilScore)} band.`);
  } else {
    reasons.push('CIBIL is unknown — the band is widened ±2% to reflect missing data.');
  }

  // Bounce / high-cost debt
  if (input.recentBounces.kind === 'known' && input.recentBounces.value > 0) {
    reasons.push(`${input.recentBounces.value} recent EMI bounce(s) will be visible to the lender.`);
  }
  if (input.highInterestDebtRatio > 0.25) {
    reasons.push(`${Math.round(input.highInterestDebtRatio * 100)}% of income already goes to high-cost debt.`);
  }

  // Tenure cap
  const cappedTenure = result.recommendedTenureMonths;
  if (cappedTenure < input.requestedTenureMonths) {
    reasons.push(`Tenure is capped at ${cappedTenure} months so the loan ends by age 60.`);
  }

  // Verdict context
  if (result.verdict.verdict === 'Borrow Less') {
    reasons.push(`Your safe capacity (${inr(result.capacity.borrowerSafeCapacity)}) is below your ask (${inr(input.requestedAmount.kind === 'known' ? input.requestedAmount.value : 0)}) — borrow the safe amount, not the original ask.`);
  }

  return reasons.slice(0, 5);
}

function scoreBand(score: number): string {
  if (score >= 780) return 'prime';
  if (score >= 740) return 'mid-prime';
  if (score >= 700) return 'sub-prime';
  return 'low-prime';
}